numbers = [1,2,3,6,4,6]
numbers.append(20)
numbers.insert(0, 25)
numbers.remove(3)
#numbers.clear()
numbers.pop()
numbers.index(6)
numbers.sort()
numbers.reverse()
numbers2 = numbers.copy()
numbers.append(15)
print(numbers)
#print(50 in numbers)
print(numbers2)
#print(numbers.count(6))
#print(numbers)